server:
  port: 2333

lavalink:
  server:
    password: "KicoSuperMusicPass2026"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    useSeekGhosting: true

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.5"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_VR
      - TVHTML5EMBEDDED

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO